# Exports the reinforcement-learning helpers for shortest-path training.
"""Reinforcement-learning utilities for Pilgrim shortest-path models."""

from __future__ import annotations

from ..schemas.rl import (
    DistributedMultiStepTDRunSpec,
    MultiStepDDQNConfig,
    MultiStepDDQNLossState,
    MultiStepDDQNMetrics,
    MultiStepDDQNStepDiagnostics,
    MultiStepTDValueConfig,
    MultiStepTDValueLossState,
    MultiStepTDValueMetrics,
    MultiStepTDValueStepDiagnostics,
    SearchGuidedPPOAuxLossConfig,
    SearchGuidedPPOBeamSearchConfig,
    SearchGuidedPPOConfig,
    SearchGuidedPPOLossState,
    SearchGuidedPPOMetrics,
    SearchGuidedPPORewardConfig,
    SearchGuidedPPORolloutConfig,
    SearchGuidedPPOStepDiagnostics,
    SearchGuidedPPOSupervisionConfig,
    TDBehaviorPolicyConfig,
    TDFileTrackerConfig,
    TDFrontierArchiveConfig,
    TDLearningRateSchedulerConfig,
    TDLipschitzPenaltyConfig,
    TDParallelConfig,
    TDProbeEvaluationConfig,
    TDRandomWalkSamplingConfig,
    TDReplayBufferConfig,
    TDSecondaryGpuEvalConfig,
    TDTargetSamplingConfig,
)
from .composite_tracking import CompositeMultiStepTDValueTracker
from .config import (
    FittedValueIterationConfig,
    FrontierArchiveConfig,
    LipschitzPenaltyConfig,
    RandomWalkSamplingConfig,
    ReplayBufferConfig,
)
from .distributed import (
    cpu_model_state_dict,
    distributed_rank,
    distributed_world_size,
    is_distributed_initialized,
    is_main_process,
    load_model_state_dict,
    local_rank_from_env,
    split_evenly,
    synchronized_barrier,
    unwrap_model,
    wrap_model_for_ddp,
)
from .file_tracking import TDFileMetricsTracker
from .fitted_value_iteration import (
    FittedValueIterationLossState,
    FittedValueIterationMetrics,
    FittedValueIterationStepDiagnostics,
    FittedValueIterationTracker,
    FittedValueIterationTrainer,
)
from .helpers import (
    BeamSearchTargetSet,
    BeamSearchTargetStats,
    PolicyActionEvaluation,
    PolicyValueOutput,
    ReverseTrajectorySupervisionBatch,
    apply_actions,
    beam_action_reward_bonus,
    collect_beam_search_targets,
    compute_double_q_targets_from_transition_batch,
    compute_lipschitz_actor_critic_loss,
    compute_n_step_double_q_targets,
    compute_supervised_policy_value_losses,
    concatenate_reverse_trajectory_batches,
    evaluate_policy_actions,
    evaluate_q_values,
    evaluate_selected_q_values,
    forward_policy_value,
    greedy_actions_from_q,
    greedy_policy_actions,
    greedy_rollout_from_q,
    model_output_dim,
    normalize_advantages,
    predict_state_scores,
    sample_behavior_actions,
    sample_n_step_transitions_from_random_walks,
    sample_n_step_transitions_from_states,
    sample_policy_actions,
    sample_reverse_trajectory_supervision_from_random_walks,
    state_values_from_q,
    subsample_reverse_trajectory_batch,
)
from .multistep_ddqn_tracking import MultiStepDDQNTracker
from .multistep_double_q_learning import MultiStepDDQNTrainer
from .multistep_td_tracking import MultiStepTDValueTracker
from .multistep_td_value_iteration import MultiStepTDValueTrainer
from .policies import greedy_actions_from_value, greedy_rollout_from_value
from .replay import (
    FrontierStateArchive,
    TensorReplayBuffer,
    TransitionBatch,
    TransitionReplayBuffer,
)
from .rollout_buffer import PolicyRolloutBatch, PolicyRolloutBuffer
from .search_guided_ppo import SearchGuidedPPOTrainer
from .search_guided_ppo_tracking import SearchGuidedPPOTracker
from .supervision_archive import (
    PolicySupervisionArchive,
    PolicySupervisionBatch,
    concatenate_policy_supervision_batches,
    subsample_policy_supervision_batch,
)
from .transitions import (
    SampledBackupConfig,
    combine_truncated_td_lambda_targets,
    compute_bellman_value_targets,
    compute_n_step_value_target_sequence,
    compute_n_step_value_targets,
    compute_sampled_n_step_value_target_sequence,
    compute_sampled_n_step_value_targets,
    compute_sampled_td_lambda_value_targets,
    compute_td_lambda_value_targets,
    enumerate_neighbor_states,
)

__all__ = [
    "BeamSearchTargetSet",
    "BeamSearchTargetStats",
    "CompositeMultiStepTDValueTracker",
    "DistributedMultiStepTDRunSpec",
    "FittedValueIterationConfig",
    "FittedValueIterationLossState",
    "FittedValueIterationMetrics",
    "FittedValueIterationStepDiagnostics",
    "FittedValueIterationTracker",
    "FittedValueIterationTrainer",
    "FrontierArchiveConfig",
    "FrontierStateArchive",
    "LipschitzPenaltyConfig",
    "MultiStepDDQNConfig",
    "MultiStepDDQNLossState",
    "MultiStepDDQNMetrics",
    "MultiStepDDQNStepDiagnostics",
    "MultiStepDDQNTracker",
    "MultiStepDDQNTrainer",
    "MultiStepTDValueConfig",
    "MultiStepTDValueLossState",
    "MultiStepTDValueMetrics",
    "MultiStepTDValueStepDiagnostics",
    "MultiStepTDValueTracker",
    "MultiStepTDValueTrainer",
    "PolicyActionEvaluation",
    "PolicyRolloutBatch",
    "PolicyRolloutBuffer",
    "PolicySupervisionArchive",
    "PolicySupervisionBatch",
    "PolicyValueOutput",
    "RandomWalkSamplingConfig",
    "ReplayBufferConfig",
    "ReverseTrajectorySupervisionBatch",
    "SampledBackupConfig",
    "SearchGuidedPPOAuxLossConfig",
    "SearchGuidedPPOBeamSearchConfig",
    "SearchGuidedPPOConfig",
    "SearchGuidedPPOLossState",
    "SearchGuidedPPOMetrics",
    "SearchGuidedPPORewardConfig",
    "SearchGuidedPPORolloutConfig",
    "SearchGuidedPPOStepDiagnostics",
    "SearchGuidedPPOSupervisionConfig",
    "SearchGuidedPPOTracker",
    "SearchGuidedPPOTrainer",
    "TDBehaviorPolicyConfig",
    "TDFileMetricsTracker",
    "TDFileTrackerConfig",
    "TDFrontierArchiveConfig",
    "TDLearningRateSchedulerConfig",
    "TDLipschitzPenaltyConfig",
    "TDParallelConfig",
    "TDProbeEvaluationConfig",
    "TDRandomWalkSamplingConfig",
    "TDReplayBufferConfig",
    "TDSecondaryGpuEvalConfig",
    "TDTargetSamplingConfig",
    "TensorReplayBuffer",
    "TransitionBatch",
    "TransitionReplayBuffer",
    "apply_actions",
    "beam_action_reward_bonus",
    "collect_beam_search_targets",
    "combine_truncated_td_lambda_targets",
    "compute_bellman_value_targets",
    "compute_double_q_targets_from_transition_batch",
    "compute_lipschitz_actor_critic_loss",
    "compute_n_step_double_q_targets",
    "compute_n_step_value_target_sequence",
    "compute_n_step_value_targets",
    "compute_sampled_n_step_value_target_sequence",
    "compute_sampled_n_step_value_targets",
    "compute_sampled_td_lambda_value_targets",
    "compute_supervised_policy_value_losses",
    "compute_td_lambda_value_targets",
    "concatenate_policy_supervision_batches",
    "concatenate_reverse_trajectory_batches",
    "cpu_model_state_dict",
    "distributed_rank",
    "distributed_world_size",
    "enumerate_neighbor_states",
    "evaluate_policy_actions",
    "evaluate_q_values",
    "evaluate_selected_q_values",
    "forward_policy_value",
    "greedy_actions_from_q",
    "greedy_actions_from_value",
    "greedy_policy_actions",
    "greedy_rollout_from_q",
    "greedy_rollout_from_value",
    "is_distributed_initialized",
    "is_main_process",
    "load_model_state_dict",
    "local_rank_from_env",
    "model_output_dim",
    "normalize_advantages",
    "predict_state_scores",
    "sample_behavior_actions",
    "sample_n_step_transitions_from_random_walks",
    "sample_n_step_transitions_from_states",
    "sample_policy_actions",
    "sample_reverse_trajectory_supervision_from_random_walks",
    "split_evenly",
    "state_values_from_q",
    "subsample_policy_supervision_batch",
    "subsample_reverse_trajectory_batch",
    "synchronized_barrier",
    "unwrap_model",
    "wrap_model_for_ddp",
]
